apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: pensjon-opptjening-oppgave-topic-q2
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
#  annotations:
#    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete # Kafka will discard old segments when retention time or size limit has been reached
    minimumInSyncReplicas: 1
    partitions: 6
    replication: 3
    retentionBytes: -1 # Messages will never get deleted because of disk space
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: pensjonopptjening
      application: pensjon-opptjening-oppgave-q2
      access: read