kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-oppgave-q2
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: OPPGAVE_URL
      value: https://oppgave.dev.intern.nav.no/api/v1/oppgaver
    - name: OPPGAVE_API_ID
      value: dev-fss.oppgavehandtering.oppgave
    - name: OPPGAVE_TOPIC
      value: pensjonopptjening.pensjon-opptjening-oppgave-topic-q2
  image: {{ image }}
  ingresses:
    - https://pensjon-opptjening-oppgave-q2.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi