name: Deploy topics dev-gcp q2

on:
  push:
    branches:
      - master
    paths:
      - 'nais/topics/pensjon-opptjening-oppgave-topic-q2.yaml'
jobs:
  deploy_topics:
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v2

      - name: 'Deploy topic to dev-gcp q2'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/pensjon-opptjening-oppgave-topic-q2.yaml